name: Commitlint
on:
  push: { branches: ["**"] }
  pull_request: { branches: ["**"] }

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v4
        with:
          config-file: commitlint.config.cjs
